#!/bin/sh
# Generate a working .env — only when there isn't one already.
#
# Never merges, never appends, never rewrites. If .env exists we leave it
# completely alone: it holds the only copy of the encryption key, and silently
# rotating that would make every stored credential unreadable.
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
ENV_FILE="$ROOT/.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists — leaving it alone."
  echo "  make doctor   check it"
  echo "  make credentials   show the admin login"
  exit 0
fi

# Hex only. These values get spliced into a PostgreSQL URL, and base64's "/"
# terminates the URL authority — that exact bug is why this script exists.
# (APP_ENCRYPTION_KEY never enters a URL, so base64 is fine there.)
rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  else
    # POSIX fallback so this works without openssl.
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

rand_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32
  else
    # crypto.ts accepts a long hex string as passphrase material (scrypt path).
    rand_hex 32
  fi
}

PORT_VALUE="${PORT:-8080}"
ADMIN_EMAIL="${SEED_ADMIN_EMAIL:-admin@example.com}"
ADMIN_PASSWORD="${SEED_ADMIN_PASSWORD:-$(rand_hex 12)}"

# Write 0600 from the start — never world-readable, not even for an instant.
umask 077
TMP="$ENV_FILE.tmp.$$"
trap 'rm -f "$TMP"' EXIT INT TERM

cat > "$TMP" <<EOF
# Generated by "make up" on $(date -u '+%Y-%m-%d %H:%M UTC').
#
# This file holds the ONLY copy of your encryption key. Keep it, back it up,
# and never commit it. Losing APP_ENCRYPTION_KEY makes every stored server
# credential permanently unreadable.
#
# Every available setting is documented in docs/CONFIGURATION.md.

NODE_ENV=production
PORT=$PORT_VALUE
WEB_ORIGIN=http://localhost:$PORT_VALUE

# Database. Hex on purpose: the password goes into a connection URL.
POSTGRES_PASSWORD=$(rand_hex 24)

# Session signing.
BETTER_AUTH_SECRET=$(rand_hex 32)

# At-rest encryption for stored server credentials.
APP_ENCRYPTION_KEY=$(rand_key)

# First-run admin. Change the password after signing in.
SEED_ADMIN_EMAIL=$ADMIN_EMAIL
SEED_ADMIN_PASSWORD=$ADMIN_PASSWORD
EOF

mv "$TMP" "$ENV_FILE"
trap - EXIT INT TERM
chmod 600 "$ENV_FILE"

# Run under sudo (common when the user isn't in the docker group) the file would
# otherwise end up root-owned and 0600, locking the user out of their own .env.
if [ -n "${SUDO_USER:-}" ]; then
  chown "$SUDO_USER" "$ENV_FILE" 2>/dev/null || true
fi

echo "Generated .env (mode 600) with fresh secrets."
